swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Descartes API
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /online:
    get:
      operationId: "status.online"
      tags:
        - "Status"
      responses:
        200:
          description: "Server is active"
  /map/create:
    get:
      operationId: "map.build_map"
      tags:
        - "Map"
      responses:
        200:
          description: "Map creation via endpoint"
  /resource/limited:
    get:
      operationId: "resource.get_limited"
      tags:
        - "Resource"
      summary: "The people data structure supported by the server application"
      description: "Read the list of people"
      responses:
        200:
          description: "Successful read people list operation"
          schema:
            type: "array"
            items:
              properties:
                resource_id:
                  type: string
                author:
                  type: string
                name:
                  type: string
                reason:
                  type: string
                size:
                  type: number
                uri:
                  type: string
                last_modified:
                  type: string
                created_at:
                  type: string
                updated_at:
                  type: string
                x:
                  type: number
                y:
                  type: number
                z:
                  type: number
  /resource/all:
    get:
      operationId: "resource.get_all"
      tags:
        - "Resource"
      summary: "The people data structure supported by the server application"
      description: "Read the list of people"
      responses:
        200:
          description: "Successful read people list operation"
          schema:
            type: "array"
            items:
              properties:
                resource_id:
                  type: string
                author:
                  type: string
                name:
                  type: string
                reason:
                  type: string
                size:
                  type: number
                uri:
                  type: string
                last_modified:
                  type: string
                created_at:
                  type: string
                updated_at:
                  type: string
                x:
                  type: number
                y:
                  type: number
                z:
                  type: number
  /resource/{resource_id}:
    get:
      operationId: "resource.get_resource"
      tags:
        - "Resource"
      summary: "The people data structure supported by the server application"
      description: "Read the list of people"
      parameters:
        - name: resource_id
          in: path
          description: Id of the person to get
          type: integer
          required: True
      responses:
        200:
          description: "Successful read people list operation"
          schema:
            type: "object"
            items:
              properties:
                resource_id:
                  type: string
                author:
                  type: string
                name:
                  type: string
                reason:
                  type: string
                size:
                  type: number
                uri:
                  type: string
                last_modified:
                  type: string
                created_at:
                  type: string
                updated_at:
                  type: string
                x:
                  type: number
                y:
                  type: number
                z:
                  type: number
  /files/{filename}:
    get:
      operationId: "resource.get_file"
      tags:
        - "Resource"
      summary: "The people data structure supported by the server application"
      description: "Read the list of people"
      parameters:
        - name: filename
          in: path
          description: Id of the person to get
          type: string
          required: True
      responses:
        200:
          description: "Successful read people list operation"
          schema:
            type: file
  /resource/create/:
    post:
      tags:
        - "Resource"
      description: "Add a new student"
      operationId: "resource.create_resource"
      consumes:
        - multipart/form-data
      parameters:
        - name: file
          in: formData
          description: Id of the person to get
          type: file
          required: True
        - name: name
          in: formData
          description: Id of the person to get
          type: string
          required: True
        - name: lastModified
          in: formData
          description: Id of the person to get
          type: string
          required: True
        - name: reason
          in: formData
          description: Id of the person to get
          type: string
          required: True
      responses:
        200:
          description: "Successful read people list operation"
          schema:
            type: "object"
  /resource/update/{resource_id}:
    post:
      tags:
        - "Resource"
      description: "Add a new student"
      operationId: "resource.update_resource"
      parameters:
        - name: resource_id
          in: path
          description: Id of the person to get
          type: integer
          required: True
      responses:
        200:
          description: "Successful read people list operation"
          schema:
            type: "object"

  #   post:
  #     operationId: "resource.create_resource"
  #     tags:
  #       - "Resource"
  #     summary: "The people data structure supported by the server application"
  #     description: "Read the list of people"
  #     parameters:
  #       - name: file
  #         in: form
  #         description: Id of the person to get
  #         type: file
  #         required: True
  #     responses:
  #       200:
  #         description: "Successful read people list operation"
  #         schema:
  #           type: "object"